// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Universal_server.Data;

#nullable disable

namespace Universal_server.Migrations
{
    [DbContext(typeof(UniversalDbContext))]
    [Migration("20251221075015_addFeatureTBL")]
    partial class addFeatureTBL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Universal_server.Models.Activiity", b =>
                {
                    b.Property<int>("Activity_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Activity_id"));

                    b.Property<int>("Business_id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Insert_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Insert_on")
                        .HasColumnType("date");

                    b.Property<bool>("visible")
                        .HasColumnType("bit");

                    b.HasKey("Activity_id");

                    b.HasIndex("Business_id");

                    b.ToTable("Activiities");
                });

            modelBuilder.Entity("Universal_server.Models.Activity_Service", b =>
                {
                    b.Property<int>("Activity_id")
                        .HasColumnType("int");

                    b.Property<int>("Service_id")
                        .HasColumnType("int");

                    b.HasKey("Activity_id", "Service_id");

                    b.HasIndex("Service_id");

                    b.ToTable("Activity_Services");
                });

            modelBuilder.Entity("Universal_server.Models.Address", b =>
                {
                    b.Property<int>("Address_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Address_id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Insert_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Insert_on")
                        .HasColumnType("date");

                    b.Property<string>("Line_1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Line_2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Post_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("visible")
                        .HasColumnType("bit");

                    b.HasKey("Address_id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Universal_server.Models.Business", b =>
                {
                    b.Property<int>("Business_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Business_id"));

                    b.Property<string>("Business_email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Business_fb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Business_google")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Business_instgram")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Business_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Business_phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Business_tiktok")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Business_webSite")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Business_whatsapp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Business_youtube")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Insert_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Insert_on")
                        .HasColumnType("date");

                    b.Property<bool>("Is_active")
                        .HasColumnType("bit");

                    b.Property<bool>("visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Business_id");

                    b.HasIndex("CountryId");

                    b.ToTable("Businesses");
                });

            modelBuilder.Entity("Universal_server.Models.Business_Address", b =>
                {
                    b.Property<int>("Business_id")
                        .HasColumnType("int");

                    b.Property<int>("Address_id")
                        .HasColumnType("int");

                    b.Property<string>("Insert_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Insert_on")
                        .HasColumnType("date");

                    b.Property<bool>("visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Business_id", "Address_id");

                    b.HasIndex("Address_id");

                    b.ToTable("Business_Addresses");
                });

            modelBuilder.Entity("Universal_server.Models.Business_BusinessType", b =>
                {
                    b.Property<int>("Business_id")
                        .HasColumnType("int");

                    b.Property<int>("Business_type_id")
                        .HasColumnType("int");

                    b.Property<string>("Insert_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Insert_on")
                        .HasColumnType("date");

                    b.Property<bool>("visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Business_id", "Business_type_id");

                    b.HasIndex("Business_type_id");

                    b.ToTable("Business_BusinessTypes");
                });

            modelBuilder.Entity("Universal_server.Models.Business_Service", b =>
                {
                    b.Property<int>("Business_id")
                        .HasColumnType("int");

                    b.Property<int>("Service_id")
                        .HasColumnType("int");

                    b.HasKey("Business_id", "Service_id");

                    b.HasIndex("Service_id");

                    b.ToTable("Business_Services");
                });

            modelBuilder.Entity("Universal_server.Models.Business_type", b =>
                {
                    b.Property<int>("Business_type_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Business_type_id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Insert_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Insert_on")
                        .HasColumnType("date");

                    b.Property<bool>("visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Business_type_id");

                    b.ToTable("Business_types");
                });

            modelBuilder.Entity("Universal_server.Models.Category", b =>
                {
                    b.Property<int>("Category_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Category_id"));

                    b.Property<string>("Insert_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Insert_on")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Category_id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Universal_server.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Insert_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Insert_on")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("CountryId");

                    b.ToTable("Countries");
                });

            modelBuilder.Entity("Universal_server.Models.Feature", b =>
                {
                    b.Property<int>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeatureId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Service_id")
                        .HasColumnType("int");

                    b.HasKey("FeatureId");

                    b.HasIndex("Service_id");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("Universal_server.Models.IdentityUserData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Universal_server.Models.Inventory", b =>
                {
                    b.Property<int>("Inventory_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Inventory_id"));

                    b.Property<int?>("Category_id")
                        .HasColumnType("int");

                    b.Property<decimal?>("Depth")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Insert_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Insert_on")
                        .HasColumnType("date");

                    b.Property<string>("InternetId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Platform_id")
                        .HasColumnType("int");

                    b.Property<string>("Product_description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Size_id")
                        .HasColumnType("int");

                    b.Property<int?>("Size_id1")
                        .HasColumnType("int");

                    b.Property<string>("Sku")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Upc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Inventory_id");

                    b.HasIndex("Category_id");

                    b.HasIndex("Platform_id");

                    b.HasIndex("Size_id1");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("Universal_server.Models.Inventory_business", b =>
                {
                    b.Property<int>("Inventory_business_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Inventory_business_id"));

                    b.Property<int>("Business_id")
                        .HasColumnType("int");

                    b.Property<string>("Insert_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Insert_on")
                        .HasColumnType("date");

                    b.Property<int>("Inventory_id")
                        .HasColumnType("int");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<bool>("visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Inventory_business_id");

                    b.HasIndex("Business_id");

                    b.HasIndex("Inventory_id");

                    b.ToTable("Inventory_businesses");
                });

            modelBuilder.Entity("Universal_server.Models.Inventoy_images", b =>
                {
                    b.Property<int>("Inventoy_images_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Inventoy_images_id"));

                    b.Property<string>("Insert_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Insert_on")
                        .HasColumnType("date");

                    b.Property<int>("Inventory_id")
                        .HasColumnType("int");

                    b.Property<string>("Inventoy_images_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Inventoy_images_id");

                    b.HasIndex("Inventory_id");

                    b.ToTable("Inventoy_images");
                });

            modelBuilder.Entity("Universal_server.Models.Platform", b =>
                {
                    b.Property<int>("Platform_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Platform_id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Insert_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Insert_on")
                        .HasColumnType("date");

                    b.Property<bool>("visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Platform_id");

                    b.ToTable("Platforms");
                });

            modelBuilder.Entity("Universal_server.Models.Service", b =>
                {
                    b.Property<int>("Service_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Service_id"));

                    b.Property<int?>("Activity_id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Insert_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Insert_on")
                        .HasColumnType("date");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<bool>("visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Service_id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Universal_server.Models.Size", b =>
                {
                    b.Property<int>("Size_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Size_id"));

                    b.Property<int?>("Category_id")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Insert_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Insert_on")
                        .HasColumnType("date");

                    b.Property<bool>("visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Size_id");

                    b.HasIndex("Category_id");

                    b.ToTable("Sizes");
                });

            modelBuilder.Entity("Universal_server.Models.System_gateway", b =>
                {
                    b.Property<int>("System_gateway_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("System_gateway_id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Insert_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Insert_on")
                        .HasColumnType("date");

                    b.Property<bool>("visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("System_gateway_id");

                    b.ToTable("System_gatewaies");
                });

            modelBuilder.Entity("Universal_server.Models.System_sectore", b =>
                {
                    b.Property<int>("System_sectore_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("System_sectore_id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Insert_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Insert_on")
                        .HasColumnType("date");

                    b.Property<bool>("visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("System_sectore_id");

                    b.ToTable("System_sectores");
                });

            modelBuilder.Entity("Universal_server.Models.System_sectore_details", b =>
                {
                    b.Property<int>("System_sectore_details_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("System_sectore_details_id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Insert_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Insert_on")
                        .HasColumnType("date");

                    b.Property<int?>("System_sectore_id")
                        .HasColumnType("int");

                    b.Property<bool>("visible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("System_sectore_details_id");

                    b.HasIndex("System_sectore_id");

                    b.ToTable("System_sectore_details");
                });

            modelBuilder.Entity("Universal_server.Models.UsersBusinesses", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Business_id")
                        .HasColumnType("int");

                    b.Property<string>("Insert_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Insert_on")
                        .HasColumnType("date");

                    b.Property<bool>("visible")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "Business_id");

                    b.HasIndex("Business_id");

                    b.ToTable("UsersBusinesseses");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Universal_server.Models.IdentityUserData", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Universal_server.Models.IdentityUserData", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Universal_server.Models.IdentityUserData", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Universal_server.Models.IdentityUserData", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Universal_server.Models.Activiity", b =>
                {
                    b.HasOne("Universal_server.Models.Business", "business")
                        .WithMany("Activities")
                        .HasForeignKey("Business_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("business");
                });

            modelBuilder.Entity("Universal_server.Models.Activity_Service", b =>
                {
                    b.HasOne("Universal_server.Models.Activiity", "Activiity")
                        .WithMany("Activity_Services")
                        .HasForeignKey("Activity_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Universal_server.Models.Service", "Service")
                        .WithMany("Activity_Services")
                        .HasForeignKey("Service_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activiity");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Universal_server.Models.Business", b =>
                {
                    b.HasOne("Universal_server.Models.Country", "Country")
                        .WithMany("Businesses")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Universal_server.Models.Business_Address", b =>
                {
                    b.HasOne("Universal_server.Models.Address", "Address")
                        .WithMany("BusinessAddresses")
                        .HasForeignKey("Address_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Universal_server.Models.Business", "Business")
                        .WithMany("BusinessAddresses")
                        .HasForeignKey("Business_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Business");
                });

            modelBuilder.Entity("Universal_server.Models.Business_BusinessType", b =>
                {
                    b.HasOne("Universal_server.Models.Business", "Business")
                        .WithMany("BusinessTypes")
                        .HasForeignKey("Business_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Universal_server.Models.Business_type", "BusinessType")
                        .WithMany("BusinessTypes")
                        .HasForeignKey("Business_type_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("BusinessType");
                });

            modelBuilder.Entity("Universal_server.Models.Business_Service", b =>
                {
                    b.HasOne("Universal_server.Models.Business", "Business")
                        .WithMany("Business_Services")
                        .HasForeignKey("Business_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Universal_server.Models.Service", "Service")
                        .WithMany("Business_Services")
                        .HasForeignKey("Service_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Universal_server.Models.Feature", b =>
                {
                    b.HasOne("Universal_server.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("Service_id");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Universal_server.Models.Inventory", b =>
                {
                    b.HasOne("Universal_server.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("Category_id");

                    b.HasOne("Universal_server.Models.Platform", "platform")
                        .WithMany()
                        .HasForeignKey("Platform_id");

                    b.HasOne("Universal_server.Models.Size", "Size")
                        .WithMany()
                        .HasForeignKey("Size_id1");

                    b.Navigation("Category");

                    b.Navigation("Size");

                    b.Navigation("platform");
                });

            modelBuilder.Entity("Universal_server.Models.Inventory_business", b =>
                {
                    b.HasOne("Universal_server.Models.Business", "Business")
                        .WithMany()
                        .HasForeignKey("Business_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Universal_server.Models.Inventory", "Inventory")
                        .WithMany()
                        .HasForeignKey("Inventory_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Universal_server.Models.Inventoy_images", b =>
                {
                    b.HasOne("Universal_server.Models.Inventory", "Inventory")
                        .WithMany("inventoy_Images")
                        .HasForeignKey("Inventory_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inventory");
                });

            modelBuilder.Entity("Universal_server.Models.Size", b =>
                {
                    b.HasOne("Universal_server.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("Category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Universal_server.Models.System_sectore_details", b =>
                {
                    b.HasOne("Universal_server.Models.System_sectore", "system_Sectore")
                        .WithMany()
                        .HasForeignKey("System_sectore_id");

                    b.Navigation("system_Sectore");
                });

            modelBuilder.Entity("Universal_server.Models.UsersBusinesses", b =>
                {
                    b.HasOne("Universal_server.Models.Business", "Business")
                        .WithMany("UsersBusinesses")
                        .HasForeignKey("Business_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Universal_server.Models.IdentityUserData", "UserData")
                        .WithMany("UsersBusinesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("UserData");
                });

            modelBuilder.Entity("Universal_server.Models.Activiity", b =>
                {
                    b.Navigation("Activity_Services");
                });

            modelBuilder.Entity("Universal_server.Models.Address", b =>
                {
                    b.Navigation("BusinessAddresses");
                });

            modelBuilder.Entity("Universal_server.Models.Business", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("BusinessAddresses");

                    b.Navigation("BusinessTypes");

                    b.Navigation("Business_Services");

                    b.Navigation("UsersBusinesses");
                });

            modelBuilder.Entity("Universal_server.Models.Business_type", b =>
                {
                    b.Navigation("BusinessTypes");
                });

            modelBuilder.Entity("Universal_server.Models.Country", b =>
                {
                    b.Navigation("Businesses");
                });

            modelBuilder.Entity("Universal_server.Models.IdentityUserData", b =>
                {
                    b.Navigation("UsersBusinesses");
                });

            modelBuilder.Entity("Universal_server.Models.Inventory", b =>
                {
                    b.Navigation("inventoy_Images");
                });

            modelBuilder.Entity("Universal_server.Models.Service", b =>
                {
                    b.Navigation("Activity_Services");

                    b.Navigation("Business_Services");
                });
#pragma warning restore 612, 618
        }
    }
}
